### ISSUE TITLE
SwiftLint JSON deserialization fails

### ISSUE THREAD

**Issue by ziadtamim** [danger/swift#266] opened 2019-08-30 13:46 UTC
Calling `SwiftLint.lint()` in the `Dangerfile.swift` is giving the issue below. The project is running under Xcode 11 beta. 

```
Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.
```

**Comment by f-meloni** [comment] 2019-08-31 22:20
I think is not related to Xcode 11, but more something related to Swiftlint itself, can you please paste here the entire error?

**Comment by f-meloni** [comment] 2019-09-29 14:39
Closing because I didn't receive any update, feel free to reopen this if the problem is still there or you have an update

**Closed by f-meloni** 2019-09-29 14:39 UTC
